version: 2
updates:
  - package-ecosystem: "maven"
    directory: "UserApp"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "automerge"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "📦 deps:"